[build]
builder = "DOCKER"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[deploy.env]
PYTHONPATH = "/usr/lib/freecad/lib:/usr/lib/python3/dist-packages:/app"
LD_LIBRARY_PATH = "/usr/lib/freecad/lib"
FLASK_ENV = "production"
FLASK_DEBUG = "0"

[[mounts]]
source = "/data/uploads"
destination = "/app/uploads"

[[mounts]]
source = "/data/converted"
destination = "/app/converted"
